### ISSUE TITLE
Git Repo add doesn't honor the patterns.

### ISSUE THREAD

**Issue by jupiter2359media** [layerhq/gradle-git-repo-plugin#15]
Hi, firstly, thank you very much for the great plugin.
Secondly, I have tried it today and have a problem: it seems like this line `gitRepo.add(patterns: "*")` doesn't work. It doesn't include the new files to the commit. So the commit contains no file change.

I'm quite new to develop gradle plugin so I cannot do much about it. Are there any solutions for this?

**Comment by drapp** [comment]
I suspect changing this * to a . would fix it, but I need to test the fix
https://github.com/layerhq/gradle-git-repo-plugin/blob/master/src/main/groovy/com/layer/gradle/gitrepo/GitRepoPlugin.groovy#L53

**Comment by drapp** [comment]
fixed in `2.0.2`

**Comment by IRuth** [comment]
Could you please publish version 2.0.2 to maven central? The latest version [there is 2.0.1](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.layer%22). Thanks.

**Comment by drapp** [comment]
It should be up there now, sorry, I never actually hit the release button apparently

**Comment by IRuth** [comment]
Thanks!
