### ISSUE TITLE
distribute on maven central

### ISSUE THREAD

**Issue by paleozogt** [layerhq/gradle-git-repo-plugin#2]
It would be great if gradle-git-repo-plugin were distributed via Maven Central (or jcenter).  I realize this is sort of an ironic request, given the functionality that this plugin provides.  However, I'd really like to only use git as a maven repo when absolutely necessary (e.g., for my own repos).

**Comment by drapp** [comment]
That definitely makes sense.  I'll get it up there as soon as I find some time to do it. Is going through sonatype still the best way? It's been a while since I've done this

**Comment by paleozogt** [comment]
To be honest, I've never done it before.  :)

**Comment by drapp** [comment]
it's up there now, check out the readme

**Comment by paleozogt** [comment]
Thanks!
