### ISSUE TITLE
build can't find git-depended project

### ISSUE THREAD

**Issue by claym** [layerhq/gradle-git-repo-plugin#23]
I can determine that the repo is being download, but the build process can't seem to find it.

It's being created in ~user/.gitRepos/listened-api/listened-api/

My sourcing build looks like this: https://gist.github.com/claym/362c2d8ef6caed918571

The target project is here: https://github.com/claym/listened-api

I don't see anything in the logs aside from a whole lot of "can't find" messages

Errors is here: 
```
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find io.listened:listened-api:1.0.
  Required by:
      io.listened:listened-worker:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Any thoughts?

**Comment by mitchhentges** [comment]
Judging by your settings, gradle will be expecting a "releases" folder within [your repository](https://github.com/claym/listened-api):
```
git("https://github.com/claym/listened-api.git", "listened-api", "master", "releases")
                                                                            ^^^^^^^^
```
However, it looks like there's only source code in there.
I'm pretty sure that this plugin only allows using a github repository as an *artifact repository* (like, a maven artifact repo).

**Comment by claym** [comment]
I ended up using jitpack.io :\

**Comment by mitchhentges** [comment]
Well, if it works :wink:
Would you be able to close this?
